## Numpy is a general purpose array-processing package in python.

It mostly deals with numbers arranged in arrays

In [2]:
import numpy as np

In [3]:
# 1-dimensional array from a python list
arr1d = np.array([1,2,3,4,5])
arr1d

array([1, 2, 3, 4, 5])

In [4]:
# 2-dimensional array from a nested python list; presents in rows and columns
arr2d = np.array([[1,2,3],[4,5,6]])
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
# an array of 0s; 3 rows and 4 columns
zeros_arr = np.zeros((3,4))
print(zeros_arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


## Array attributes


In [6]:
# Shape
shape = arr2d.shape  # returns the number of rows and columns in the array
print(shape)

zeros_arr.shape

(2, 3)


(3, 4)

In [7]:
# Size
size = arr2d.size   # returns the number of elements in the array
print(size)

zeros_arr.size

6


12

In [8]:
# Data type
data_type = arr2d.dtype
print(data_type)

zeros_arr.dtype

int64


dtype('float64')

## Array Operations

In [9]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
# Addition
addition = 2 + arr2d    # adding 2 to all the elements of the array
print(addition)

[[3 4 5]
 [6 7 8]]


In [11]:
# Subtraction
subtraction = arr2d - 3 # subtract 3 from all the elements in the array
print(subtraction)

[[-2 -1  0]
 [ 1  2  3]]


In [12]:
# Multiplication: multiplies through all the elements in the array
multiplication = 4 * arr2d
print(multiplication)

[[ 4  8 12]
 [16 20 24]]


## Aggregation Functions

In [13]:
# Sum: adds up all the elements in the array
total_sum = arr2d.sum()
print(total_sum)

21


In [14]:
# Max: maximum value of all the elements in the array
max_val = arr2d.max()
print(max_val)

6


In [15]:
# Min: minimum value of all the elements in the array
min_val = arr2d.min()
print(min_val)

1


## Indexing

In [16]:
# return rows with index 0,stop before index 1, and all columns
first_row = arr2d[0:1,:]
print(first_row)

[[1 2 3]]


In [17]:
# return row from index 1 to the last and all columns
second_row = arr2d[1:,:]
print(second_row)

[[4 5 6]]


In [18]:
# return rows with index 0,stop before index 1, and columns from index 0, stop
# before index 2
first_row_element = arr2d[0:1,0:2]
print(first_row_element)

[[1 2]]


In [19]:
# return rows from index 1 and columns from index 1
second_row_element = arr2d[1:,1:]
print(second_row_element)

[[5 6]]


## Array Manipulation

In [20]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
arr2d.shape

(2, 3)

In [22]:
#reshaping the array to a 3 by 2 array
reshape = arr2d.reshape(3,2)
reshape

array([[1, 2],
       [3, 4],
       [5, 6]])

In [23]:
#reshaping the array to a 1 by 6 array
reshape_1 =arr2d.reshape(1,6)
reshape_1

array([[1, 2, 3, 4, 5, 6]])

In [24]:
# Concatenate Arrays
arr1d = [1,2,3]
arr2d = [4,5,6]
concat_arr = np.concat([arr1d,arr2d])
print(concat_arr)

[1 2 3 4 5 6]


In [25]:
# Concatenate Arrays 2
arr1d = np.array([1,2,3])
concat_arr2 = np.concatenate([arr1d,np.array([4,5,6])])
print(concat_arr2)

[1 2 3 4 5 6]


In [26]:
# append
arr1d = np.array([1,2,3])
append_arr = np.append(arr1d,[4,5,6])
print(append_arr)

[1 2 3 4 5 6]


In [27]:
#append to 2 dimensional array
arr2d = np.array([[1,2,3],[4,5,6]])
append_arr1 = np.append(arr2d,[7,8,9])
print(append_arr1)

[1 2 3 4 5 6 7 8 9]


## Broadcasting

Broadcasting in NumPy allows operations between arrays of different shapes by automatically adjusting their dimensions to be compatible.
Broadcasting enables operations between arrays of different shapes without requiring explicit reshaping.

In [28]:
# automatically stretches the single number so it can be added to each item in
# the list
a = np.array([1,2,3])
b = 4
print(a+b)

[5 6 7]


In [29]:
a = np.array([1,2,3])
b = 6
print(a*b)

[ 6 12 18]


## Random Number Generation

In [30]:
# random.rand() function generates random numbers between 0 and 1
random_numbers = np.random.rand(3,3)
print(random_numbers)

[[0.24316575 0.97038224 0.34763643]
 [0.85748978 0.09552258 0.92407702]
 [0.29553234 0.60339306 0.19214069]]


In [31]:
# random.randint() function generates random integers within specified range
# including the lower boundary but excluding the upper boundary
random_numbers_ = np.random.randint(0,100,6)
print(random_numbers_)

[22 88 71 35 83 92]


In [33]:
# reshaping generated random numbers
random_numbers_ = np.random.randint(0,100,6).reshape(3,2)
print(random_numbers_)

[[26 74]
 [83 38]
 [39 65]]


In [35]:
# random.randn() returns random numbers that fall within a normal distribution
random_numbers1 = np.random.randn(4, 6)
print(random_numbers1)

[[-1.34753561  0.46112433 -0.96709405 -0.23716098 -0.14731884 -0.13699537]
 [-0.57334734 -0.23877266 -0.22472715 -1.12255251  0.40859334  0.40680501]
 [ 0.97429923 -0.10885818  1.34538378  0.58548663  0.24740872 -0.04579697]
 [-1.31010495  0.20397074 -1.04268992 -0.66718208  0.7319623   1.00494984]]


In [38]:
items = np.array (["A", "B", "C", "D"])
# random.choice() randomly picks elements from the array
random_numbers2 = np.random.choice(items, 3)
print(random_numbers2)

['D' 'A' 'D']


## Linear Algebra

In [39]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [40]:
# matrix addition
print(A + B)

[[ 6  8]
 [10 12]]


In [41]:
# matrix subtraction
print(A - B)

[[-4 -4]
 [-4 -4]]


In [42]:
# matrix multiplication (Element-wise multiplication)
print(A * B)

[[ 5 12]
 [21 32]]


In [43]:
# matrix multiplication
print(A @ B)

[[19 22]
 [43 50]]


In [44]:
result = np.matmul(A,B)
print(result)

[[19 22]
 [43 50]]


In [45]:
# Standard Matrix multiplication
F = np.dot(A,B)
print(F)

[[19 22]
 [43 50]]


In [48]:
A = np.array([[5,6,7],[8,9,0]])
A
# Transpose of a matrix
transpose_A = np.transpose(A)
print(transpose_A)

[[5 8]
 [6 9]
 [7 0]]


In [50]:
B = np.array([[1,2],[3,4]])
# Inverse of a matrix
B_inv = np.linalg.inv(B)
print(B_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [51]:
# identity matrix
identity_matrix = np.eye(6)
print(identity_matrix)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [52]:
# determinant of a matrix: a single numerical value computed by a square matrix
determinant = np.linalg.det(B)
print(int(determinant))

-2


## Deleting elements in an array

In [53]:
arr = np.array([1,2,3,4,5])
arr_deleted = np.delete(arr,2)
print(arr_deleted)

[1 2 4 5]


In [54]:
arr = np.array([1,2,3,4,5])
m = arr != 5
new_arr = arr[m]
print(new_arr)

[1 2 3 4]


## Statistical Functions

In [58]:
arr = np.array([11,11,12,32,41,50,7,])

In [59]:
# mean
arr_mean = np.mean(arr)
print(arr_mean)

23.428571428571427


In [60]:
# median
arr_median = np.median(arr)
print(arr_median)

12.0


In [65]:
# mode : numpy does not have the mode method, so scipy can be used
arr = np.array([11,11,12,32,11,41,50,7,])
from scipy import stats
arr_mode = stats.mode(arr,keepdims = False)
print(arr_mode)

ModeResult(mode=np.int64(11), count=np.int64(3))


In [66]:
# standard deviation
arr_std = np.std(arr)
print(arr_std)

15.54378895250447
